name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  labels:
    description: 'labels to filter from'
    required: false
    default: []
  issue_number:
    description: 'the issues number to update'
    required: true
  org_name:
    description: 'github org to use'
    required: true
  repo_name:
    description: 'github repo to use'
    required: true



# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js